name: Musl CI

on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-24.04
    container: alpine:3.23

    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Linux GCC (musl)
            use-clang: false

          - name: Linux Clang (musl)
            use-clang: true


    steps:
      - name: Install dependencies
        run: |
          apk update
          apk add wget python3 py3-pip ca-certificates samurai git openssl-dev openssl pkgconf nodejs pnpm bash zstd-dev zlib-dev brotli-dev gmp-dev linux-pam-dev ${{ ( matrix.config.use-clang == true ) && 'clang21' || 'gcc musl-dev g++' }}
          echo "CC=${{ matrix.config.use-clang == true && 'clang-21' || 'gcc' }}" >> "$GITHUB_ENV"
          echo "CXX=${{ matrix.config.use-clang == true && 'clang++-21' || 'g++' }}" >> "$GITHUB_ENV"

      # NOTE: meson has no dependencies, so --break-system-packages doesn't really break anything!
      - name: Setup meson
        run: |
            pip install meson --break-system-packages

      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'
  
      - name: Configure
        run: meson setup build -Dbuildtype=release -Dsecure=enabled -Dcompression_features=zstd,br,deflate,gzip,compress -Dother_features=bcrypt,pam --fatal-meson-warnings

      - name: Build
        run: meson compile -C build
