name: Test CI

on:
    push:
        branches: ["main"]
    pull_request:
    workflow_dispatch:

jobs:
    test:
        name: Test - ${{ matrix.config.name }}
        runs-on: ${{ matrix.config.os }}-${{ matrix.config.os-version }}

        strategy:
            fail-fast: false
            matrix:
                config:
                    - name: x86_64
                      os: ubuntu
                      os-version: 24.04

                    - name: arm64
                      os: ubuntu
                      os-version: 24.04-arm

        steps:
            - uses: actions/checkout@v6
              with:
                  fetch-depth: "0"
                  submodules: "recursive"

            - name: Setup GCC
              uses: egor-tensin/setup-gcc@v2
              with:
                  version: 14
                  platform: x64 # note, this isn't really correct

            - name: Setup node
              uses: actions/setup-node@v6
              with:
                  node-version: 24

            - name: Setup pnpm
              uses: pnpm/action-setup@v5
              with:
                  version: 10

            # NOTE: meson has no dependencies, so --break-system-packages doesn't really break anything!
            - name: Setup meson
              run: |
                  pip install meson --break-system-packages

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install ninja-build openssl libssl-dev libzstd-dev zlib1g-dev libbrotli-dev wget ca-certificates bzip2 pipx libgmp-dev libpam0g-dev -y --no-install-recommends

            # NOTE: the repos hav 7.0 but we need >= 8.4, so we install gcovr with pipx (it has to much dependencies for a raw install with --break-system-packages)
            - name: Setup gcovr
              run: |
                  pipx ensurepath
                  pipx install "gcovr>=8.4"

            - name: Unit Tests
              run: |
                  meson setup test_build -Dbuildtype=debug -Db_coverage=true -Dtests=true -Dsecure=enabled -Dcompression_features=zstd,br,deflate,gzip,compress -Dother_features=bcrypt,pam --fatal-meson-warnings
                  meson compile -C test_build
                  DOCTEST_TEST_MULTIPLIER=3 meson test -C test_build --verbose -j $(nproc) -t 3
                  GCOV=gcov-14 ninja coverage -C test_build
            - name: Create Coverage Report
              uses: insightsengineering/coverage-action@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  path: ./test_build/meson-logs/coverage.xml
                  fail: false # TODO: enable after coverage is higher than 0.000001 % xD
                  # Publish the rendered output as a PR comment
                  publish: true
                  coverage-summary-title: "Code Coverage Summary"
                  togglable-report: true
                  # TODO: use the diff feature of that later when we require test coverage on PR's to not go down

            - uses: actions/upload-artifact@v6
              with:
                  name: test results - ${{ matrix.config.name }}
                  path: |
                      ./test_build/meson-logs/coverage.xml
                      ./test_build/meson-logs/coveragereport/**
